"""add prompts and prompt_versions

Revision ID: 0da6d7df2008
Revises: 7dd2b97d67bd
Create Date: 2026-05-15 14:17:44.815452

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0da6d7df2008"
down_revision: str | Sequence[str] | None = "7dd2b97d67bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("edited_by", sa.String(length=64), server_default="", nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client_apps.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_versions_client_id"), "prompt_versions", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_versions_edited_at"), "prompt_versions", ["edited_at"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_versions_task_type"), "prompt_versions", ["task_type"], unique=False
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("client_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_by", sa.String(length=64), server_default="", nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["client_apps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompts_client_id"), "prompts", ["client_id"], unique=False)
    op.create_index(
        "ix_prompts_client_unique",
        "prompts",
        ["task_type", "client_id"],
        unique=True,
        postgresql_where="client_id IS NOT NULL",
    )
    op.create_index(
        "ix_prompts_shared_unique",
        "prompts",
        ["task_type"],
        unique=True,
        postgresql_where="client_id IS NULL",
    )
    op.create_index(op.f("ix_prompts_task_type"), "prompts", ["task_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompts_task_type"), table_name="prompts")
    op.drop_index(
        "ix_prompts_shared_unique", table_name="prompts", postgresql_where="client_id IS NULL"
    )
    op.drop_index(
        "ix_prompts_client_unique", table_name="prompts", postgresql_where="client_id IS NOT NULL"
    )
    op.drop_index(op.f("ix_prompts_client_id"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_prompt_versions_task_type"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_edited_at"), table_name="prompt_versions")
    op.drop_index(op.f("ix_prompt_versions_client_id"), table_name="prompt_versions")
    op.drop_table("prompt_versions")
    # ### end Alembic commands ###
