"""add jobs and routing_rules

Revision ID: bff39a594e66
Revises: ffe8e9c8f900
Create Date: 2026-04-29 17:39:46.108384

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bff39a594e66"
down_revision: str | Sequence[str] | None = "ffe8e9c8f900"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "routing_rules",
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("preferred_model", sa.String(length=100), nullable=False),
        sa.Column("fallback_model", sa.String(length=100), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("max_tokens", sa.Integer(), server_default="1000", nullable=False),
        sa.Column("notes", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("task_type"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_app_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="5", nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), server_default="", nullable=False),
        sa.Column("model_requested", sa.String(length=100), server_default="", nullable=False),
        sa.Column("model_used", sa.String(length=100), server_default="", nullable=False),
        sa.Column("response", sa.Text(), server_default="", nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.ForeignKeyConstraint(["client_app_id"], ["client_apps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_client_app_id"), "jobs", ["client_app_id"], unique=False)
    op.create_index(op.f("ix_jobs_created_at"), "jobs", ["created_at"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(op.f("ix_jobs_task_type"), "jobs", ["task_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_task_type"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_created_at"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_client_app_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("routing_rules")
    # ### end Alembic commands ###
